# print("hello","world")
# print("hello"+"world")
# print(" \n* "*5)
# print("'hello'")
print(" "*12+" * "*1)
print(" "*9+" * "*3)
print(" "*6+" * "*5)
print(" "*4+" * "*7)
print(" "*2+" * "*9)
print(" * "*11)
